// src/capabilities/definitions.ts
// All capability definitions — the registry data layer.

import type { CapabilityDefinition } from './types'

export const ALL_CAPABILITY_DEFINITIONS: CapabilityDefinition[] = [
  // ── Core capabilities ──
  {
    id: 'conversation-list',
    category: 'core',
    label: 'List Conversations',
    description: 'Paginated conversation list with cursor navigation',
    providerMethod: 'listConversations',
    messageType: 'TEST_LIST_CONVERSATIONS',
    requiresAccount: true,
    params: [
      { name: 'cursor', type: 'string', required: false, description: 'Pagination cursor' },
      { name: 'limit', type: 'number', required: false, description: 'Max results per page' },
    ],
    returnType: 'PaginatedResult<Header>',
    icon: 'Database',
  },
  {
    id: 'message-fetch',
    category: 'core',
    label: 'Fetch Conversation',
    description: 'Download full conversation with message pairs',
    providerMethod: 'getConversation',
    messageType: 'TEST_FETCH_CONTENT',
    requiresAccount: true,
    params: [
      { name: 'conversationId', type: 'string', required: true, description: 'Conversation ID' },
    ],
    returnType: 'Conversation',
    icon: 'FileText',
  },
  {
    id: 'edit-title',
    category: 'core',
    label: 'Edit Title',
    description: 'Rename a conversation',
    providerMethod: 'editTitle',
    messageType: 'TEST_EDIT_TITLE',
    requiresAccount: true,
    params: [
      { name: 'conversationId', type: 'string', required: true, description: 'Conversation ID' },
      { name: 'title', type: 'string', required: true, description: 'New title' },
    ],
    returnType: 'void',
    icon: 'Edit3',
  },
  {
    id: 'delete-conversation',
    category: 'core',
    label: 'Delete Conversation',
    description: 'Remove a conversation from the provider',
    providerMethod: 'deleteConversation',
    messageType: 'TEST_DELETE_CONVERSATION',
    requiresAccount: true,
    params: [
      { name: 'conversationId', type: 'string', required: true, description: 'Conversation ID' },
    ],
    returnType: 'void',
    icon: 'Trash2',
  },
  {
    id: 'create-conversation',
    category: 'core',
    label: 'Create Conversation',
    description: 'Start new chat with initial prompt',
    providerMethod: 'createConversation',
    messageType: 'TEST_CREATE_CONVERSATION',
    requiresAccount: true,
    params: [
      { name: 'prompt', type: 'string', required: true, description: 'Initial prompt text' },
    ],
    returnType: 'Conversation',
    icon: 'Plus',
  },
  {
    id: 'search',
    category: 'core',
    label: 'Search Conversations',
    description: 'Text search across all conversations',
    providerMethod: 'search',
    messageType: 'TEST_SEARCH',
    requiresAccount: true,
    params: [
      { name: 'query', type: 'string', required: true, description: 'Search query text' },
    ],
    returnType: 'SearchResult[]',
    icon: 'Search',
  },
  {
    id: 'ping',
    category: 'core',
    label: 'Ping / Connectivity',
    description: 'Check if provider is reachable',
    providerMethod: 'ping',
    messageType: 'TEST_PING',
    requiresAccount: true,
    params: [],
    returnType: 'boolean',
    icon: 'CheckCircle2',
  },
  {
    id: 'get-chat-url',
    category: 'core',
    label: 'Get Chat URL',
    description: 'Build provider URL for a conversation',
    providerMethod: 'getChatUrl',
    messageType: 'TEST_GET_CHAT_URL',
    requiresAccount: false,
    params: [
      { name: 'conversationId', type: 'string', required: true, description: 'Conversation ID' },
    ],
    returnType: 'string',
    icon: 'ExternalLink',
  },

  // ── Provider capabilities ──
  {
    id: 'fetch-all-gems',
    category: 'provider',
    label: 'Fetch All Gems',
    description: 'List conversations from custom Gemini assistants',
    providerMethod: 'fetchAllGems',
    messageType: 'TEST_FETCH_ALL_GEMS',
    requiresAccount: true,
    params: [],
    returnType: 'Conversation[]',
    icon: 'Database',
  },
  {
    id: 'fetch-summary',
    category: 'provider',
    label: 'Fetch Summary',
    description: 'Get AI-generated text response (temp chat)',
    providerMethod: 'summarize',
    messageType: 'TEST_FETCH_SUMMARY',
    requiresAccount: true,
    params: [
      { name: 'prompt', type: 'string', required: true, description: 'Summary prompt' },
      { name: 'systemPrompt', type: 'string', required: false, description: 'System prompt' },
    ],
    returnType: 'string',
    icon: 'Sparkles',
  },
  {
    id: 'auto-sync',
    category: 'provider',
    label: 'Auto Sync',
    description: 'Network interception for auto-sync',
    providerMethod: 'handleNetworkActivity',
    messageType: 'auto-sync',
    requiresAccount: true,
    params: [
      { name: 'details', type: 'object', required: true, description: 'RequestDetails object' },
    ],
    returnType: 'SyncTrigger | null',
    icon: 'RefreshCw',
  },
  {
    id: 'is-offline',
    category: 'provider',
    label: 'Check Offline Status',
    description: 'Verify if account is still authenticated',
    providerMethod: 'isOffline',
    messageType: 'TEST_IS_OFFLINE',
    requiresAccount: true,
    params: [
      { name: 'accountId', type: 'string', required: true, description: 'Account ID' },
    ],
    returnType: 'boolean',
    icon: 'WifiOff',
  },
  {
    id: 'detect-accounts',
    category: 'provider',
    label: 'Detect Accounts',
    description: 'Scan for authenticated accounts',
    providerMethod: 'detectAccounts',
    messageType: 'GET_ACCOUNTS',
    requiresAccount: false,
    params: [],
    returnType: 'Account[]',
    icon: 'Users',
  },
  {
    id: 'refresh-auth',
    category: 'provider',
    label: 'Refresh Auth',
    description: 'Refresh auth token for a given account',
    providerMethod: 'refreshAuth',
    messageType: 'refresh-auth',
    requiresAccount: true,
    params: [],
    returnType: 'AuthProfile | null',
    icon: 'Key',
  },
  {
    id: 'is-authenticated',
    category: 'provider',
    label: 'Is Authenticated',
    description: 'Check if account is still authenticated',
    providerMethod: 'isAuthenticated',
    messageType: 'is-authenticated',
    requiresAccount: true,
    params: [],
    returnType: 'boolean',
    icon: 'Shield',
  },

  // ── Utility capabilities ──
  {
    id: 'download-raw',
    category: 'utility',
    label: 'Download Raw Data',
    description: 'Download N most recent conversations with raw API response, parsed messages, and media',
    messageType: 'TEST_DOWNLOAD_RAW',
    requiresAccount: true,
    params: [
      { name: 'count', type: 'number', required: false, description: 'Number of conversations (default: 1)' },
      { name: 'conversationId', type: 'string', required: false, description: 'Specific conversation ID' },
    ],
    returnType: '{ conversations: Array<{header, parsedMessages, rawApiResponse, media}> }',
    icon: 'Database',
  },
  {
    id: 'deobfuscate',
    category: 'utility',
    label: 'Deobfuscate Raw API',
    description: 'Analyze raw response and produce complete field taxonomy',
    messageType: 'TEST_DEOBFUSCATE',
    requiresAccount: true,
    params: [
      { name: 'count', type: 'number', required: false, description: 'Number of conversations (default: 1)' },
      { name: 'conversationId', type: 'string', required: false, description: 'Specific conversation ID' },
    ],
    returnType: '{ conversations: Array<{header, parsedMessages, rawApiResponse, media}> }',
    icon: 'Sparkles',
  },
  {
    id: 'download-media',
    category: 'utility',
    label: 'Download Media',
    description: 'Extract and download all media from a conversation',
    messageType: 'TEST_DOWNLOAD_MEDIA',
    requiresAccount: true,
    params: [
      { name: 'conversationId', type: 'string', required: true, description: 'Conversation ID' },
    ],
    returnType: '{ conversationId: string, media: Array<{url}> }',
    icon: 'Image',
  },
  {
    id: 'sync-missing',
    category: 'utility',
    label: 'Sync Missing from Search',
    description: 'Download conversations not in local DB',
    messageType: 'TEST_SYNC_MISSING',
    requiresAccount: true,
    params: [
      { name: 'searchResults', type: 'array', required: true, description: 'Search result IDs' },
    ],
    returnType: 'number',
    icon: 'RefreshCw',
  },
  {
    id: 'get-all-headers',
    category: 'utility',
    label: 'Get All Headers',
    description: 'Get all conversation headers for a service',
    messageType: 'GET_ALL_HEADERS',
    requiresAccount: false,
    params: [
      { name: 'serviceId', type: 'string', required: true, description: 'Service ID' },
      { name: 'accountId', type: 'string', required: false, description: 'Account ID filter' },
    ],
    returnType: 'Header[]',
    icon: 'List',
  },
  {
    id: 'fetch-media-base64',
    category: 'utility',
    label: 'Fetch Media as Base64',
    description: 'Convert remote media URLs to base64 for download',
    messageType: 'FETCH_MEDIA_AS_BASE64',
    requiresAccount: false,
    params: [
      { name: 'urls', type: 'array', required: true, description: 'Array of media URLs' },
    ],
    returnType: 'Array<{url, dataUrl?, error?}>',
    icon: 'Download',
  },
  {
    id: 'get-rate-limit-status',
    category: 'utility',
    label: 'Rate Limit Status',
    description: 'Check if provider is rate-limited',
    messageType: 'GET_RATE_LIMIT_STATUS',
    requiresAccount: false,
    params: [],
    returnType: '{ isRateLimited: boolean, serviceId: string }',
    icon: 'AlertTriangle',
  },

  // ── Bridge capabilities ──
  {
    id: 'chat-send',
    category: 'bridge',
    label: 'Send Chat Message',
    description: 'Inject prompt into Gemini textarea and click send',
    messageType: 'chat-send',
    requiresAccount: true,
    params: [
      { name: 'text', type: 'string', required: true, description: 'Prompt text' },
      { name: 'conversationId', type: 'string', required: false, description: 'Existing conversation ID' },
    ],
    returnType: 'void',
    icon: 'Send',
  },
  {
    id: 'chat-read-ui',
    category: 'bridge',
    label: 'Read Chat UI State',
    description: 'Read model selection, active tools from Gemini UI',
    messageType: 'chat-read-ui',
    requiresAccount: false,
    params: [],
    returnType: '{ model: string, tools: string[] }',
    icon: 'Eye',
  },
  {
    id: 'chat-navigate',
    category: 'bridge',
    label: 'Navigate Chat',
    description: 'Navigate Gemini tab to specific conversation',
    messageType: 'chat-navigate',
    requiresAccount: false,
    params: [
      { name: 'conversationId', type: 'string', required: true, description: 'Conversation ID' },
    ],
    returnType: 'void',
    icon: 'Navigation',
  },
  {
    id: 'chat-inject-prompt',
    category: 'bridge',
    label: 'Inject Prompt',
    description: 'Receive prompt from iframe, inject into textarea',
    messageType: 'chat-inject-prompt',
    requiresAccount: false,
    params: [
      { name: 'text', type: 'string', required: true, description: 'Prompt text' },
    ],
    returnType: 'void',
    icon: 'FileInput',
  },
  {
    id: 'chat-export-response',
    category: 'bridge',
    label: 'Export Response',
    description: 'Extract model response text from DOM',
    messageType: 'chat-export-response',
    requiresAccount: false,
    params: [],
    returnType: 'string',
    icon: 'FileOutput',
  },
  {
    id: 'chat-detect-theme',
    category: 'bridge',
    label: 'Detect Theme',
    description: 'Detect light/dark theme on Gemini page',
    messageType: 'chat-detect-theme',
    requiresAccount: false,
    params: [],
    returnType: '"light" | "dark"',
    icon: 'Palette',
  },
  {
    id: 'chat-observe-url',
    category: 'bridge',
    label: 'Observe URL Changes',
    description: 'Detect URL changes for conversation navigation via MutationObserver',
    messageType: 'chat-observe-url',
    requiresAccount: false,
    params: [],
    returnType: 'string',
    icon: 'Navigation',
  },
  {
    id: 'chat-inject-header',
    category: 'bridge',
    label: 'Inject Header',
    description: 'Inject prompt attribution header into page',
    messageType: 'chat-inject-header',
    requiresAccount: false,
    params: [
      { name: 'text', type: 'string', required: true, description: 'Header text' },
    ],
    returnType: 'void',
    icon: 'FileInput',
  },
  {
    id: 'chat-inject-selectors',
    category: 'bridge',
    label: 'Inject Selectors',
    description: 'Inject language/tone/style selector dropdowns',
    messageType: 'chat-inject-selectors',
    requiresAccount: false,
    params: [],
    returnType: 'void',
    icon: 'List',
  },
  {
    id: 'chat-inject-export-btns',
    category: 'bridge',
    label: 'Inject Export Buttons',
    description: 'Add export buttons to each message',
    messageType: 'chat-inject-export-btns',
    requiresAccount: false,
    params: [],
    returnType: 'void',
    icon: 'Download',
  },

  // ── Meta capabilities ──
  {
    id: 'get-state',
    category: 'meta',
    label: 'Get Provider State',
    description: 'Provider state overview (connected, counts, accounts)',
    messageType: 'GET_STATE',
    requiresAccount: false,
    params: [],
    returnType: 'Array<ProviderState>',
    icon: 'Activity',
  },
  {
    id: 'sync-provider',
    category: 'meta',
    label: 'Sync Provider',
    description: 'Trigger full sync for a provider',
    messageType: 'SYNC_PROVIDER',
    requiresAccount: true,
    params: [],
    returnType: '{ ok: boolean }',
    isFireAndForget: true,
    icon: 'RefreshCw',
  },
  {
    id: 'sync-conversation',
    category: 'meta',
    label: 'Sync Conversation',
    description: 'Sync single conversation',
    messageType: 'SYNC_CONVERSATION',
    requiresAccount: true,
    params: [
      { name: 'conversationId', type: 'string', required: true, description: 'Conversation ID' },
    ],
    returnType: '{ ok: boolean }',
    isFireAndForget: true,
    icon: 'RefreshCw',
  },
  {
    id: 'protocol-test-suite',
    category: 'meta',
    label: 'Protocol Test Suite',
    description: 'Full interaction cycle test — create, read, update, delete, verify',
    messageType: 'TEST_PROTOCOL_SUITE',
    requiresAccount: true,
    params: [],
    returnType: 'ProtocolTestReport',
    icon: 'TestTube',
  },
  {
    id: 'set-active-account',
    category: 'meta',
    label: 'Set Active Account',
    description: 'Set active account preference',
    messageType: 'SET_ACTIVE_ACCOUNT',
    requiresAccount: false,
    params: [
      { name: 'accountId', type: 'string', required: true, description: 'Account ID' },
    ],
    returnType: '{ ok: boolean }',
    icon: 'UserCheck',
  },
  {
    id: 'get-active-account',
    category: 'meta',
    label: 'Get Active Account',
    description: 'Get active account preference',
    messageType: 'GET_ACTIVE_ACCOUNT',
    requiresAccount: false,
    params: [],
    returnType: 'string',
    icon: 'User',
  },
  {
    id: 'get-settings',
    category: 'meta',
    label: 'Get Settings',
    description: 'Get extension settings',
    messageType: 'GET_SETTINGS',
    requiresAccount: false,
    params: [],
    returnType: 'Record<string, unknown>',
    icon: 'Settings',
  },
  {
    id: 'set-settings',
    category: 'meta',
    label: 'Set Settings',
    description: 'Update extension settings',
    messageType: 'SET_SETTINGS',
    requiresAccount: false,
    params: [
      { name: 'settings', type: 'object', required: true, description: 'Settings object' },
    ],
    returnType: '{ ok: boolean }',
    icon: 'Settings',
  },

  // ── Utility: Rate limit reset ──
  {
    id: 'reset-rate-limit',
    category: 'utility',
    label: 'Reset Rate Limit',
    description: 'Reset rate limiter state, clear auth cache, reset IDB flag',
    messageType: 'RESET_RATE_LIMIT',
    requiresAccount: false,
    params: [],
    returnType: '{ ok: boolean }',
    icon: 'AlertTriangle',
  },

  // ── Bridge: Adjust body layout ──
  {
    id: 'chat-adjust-body',
    category: 'bridge',
    label: 'Adjust Chat Body Layout',
    description: 'Modify chat-app padding/margin based on sidebar state',
    messageType: 'chat-adjust-body',
    requiresAccount: false,
    params: [
      { name: 'isOpen', type: 'boolean', required: true, description: 'Whether sidebar is open' },
      { name: 'isTransitioning', type: 'boolean', required: false, description: 'Whether in transition' },
      { name: 'appWidth', type: 'number', required: false, description: 'Panel width (default: 440)' },
    ],
    returnType: 'void',
    icon: 'Layout',
  },

  // ── Bridge: Handle submission monitoring ──
  {
    id: 'chat-handle-submission',
    category: 'bridge',
    label: 'Monitor Chat Submission',
    description: 'MutationObserver on chat-history to detect new model-response elements',
    messageType: 'chat-handle-submission',
    requiresAccount: false,
    params: [
      { name: 'promptData', type: 'object', required: false, description: 'Prompt reference data for header injection' },
    ],
    returnType: 'void',
    icon: 'Eye',
  },

  // ── Bridge: Inject continue button ──
  {
    id: 'chat-inject-continue-btn',
    category: 'bridge',
    label: 'Inject Continue Button',
    description: 'Inject continue-type selector dropdown, auto-populate textarea on change',
    messageType: 'chat-inject-continue-btn',
    requiresAccount: false,
    params: [],
    returnType: 'void',
    icon: 'Repeat',
  },

  // ── Bridge: Capture network conversation ID ──
  {
    id: 'chat-capture-network-id',
    category: 'bridge',
    label: 'Capture Network Conversation ID',
    description: 'Extract conversation ID from Performance API network request URLs',
    messageType: 'chat-capture-network-id',
    requiresAccount: false,
    params: [],
    returnType: 'string | null',
    icon: 'Network',
  },

  // ── Bridge: Cleanup stale prompt references ──
  {
    id: 'chat-cleanup-prompts',
    category: 'bridge',
    label: 'Cleanup Stale Prompts',
    description: 'Remove expired pd_id_* localStorage entries',
    messageType: 'chat-cleanup-prompts',
    requiresAccount: false,
    params: [],
    returnType: 'number',
    icon: 'Trash2',
  },

  // ── Bridge: Read active model ──
  {
    id: 'chat-read-model',
    category: 'bridge',
    label: 'Read Active Model',
    description: 'Detect which Gemini model is active (Pro, Flash, etc.) from DOM',
    messageType: 'chat-read-model',
    requiresAccount: false,
    params: [],
    returnType: 'string | null',
    icon: 'Cpu',
  },

  // ── Bridge: Set app width ──
  {
    id: 'chat-set-app-width',
    category: 'bridge',
    label: 'Set App Width',
    description: 'Set sidebar panel width via dragger interaction',
    messageType: 'chat-set-app-width',
    requiresAccount: false,
    params: [
      { name: 'width', type: 'number', required: true, description: 'Panel width in pixels' },
      { name: 'dragger', type: 'string', required: false, description: 'CSS right value' },
    ],
    returnType: 'void',
    icon: 'MoveHorizontal',
  },
]
